services:
  broker:
    build: broker/
    ports:
      - "7100:5000"
  database:
    build: 
      context: .
      dockerfile: database/Dockerfile
    volumes:
      - "/database/datab:/opt/graphdb/home"
    ports:
      - "7200:7200"