services:
  broker:
    build: broker/
    ports:
      - "7100:5000"
  database:
    build: 
      context: .
      dockerfile: database/Dockerfile
    volumes:
      - /graphdb_data:/opt/graphdb/home
    ports:
      - "7200:7200"
  web:
    build: web/
    ports:
      - "7300:5000"