services:
  broker:
    build: broker/
    ports:
      - "7100:5000"
  database:
    build: 
      context: .
      dockerfile: database/Dockerfile
    volumes:
      - C:\Users\rasmu\D0020E\circular-entity-broker/graphdb_data:/opt/graphdb/home
    ports:
      - "7200:7200"